### ISSUE TITLE
Can't open otag links on Windows

### ISSUE THREAD

**Issue by minkkinen** [andersjohansson/orgqda#1]
I noticed that otag links in the orgqda-list buffer can't be opened on Windows. I think it's because they're split on the ":" and Windows paths have that character (e.g. "c:/Users/example/file.org"), so it tries to open a nonexisting file. I'm not sure how to fix this though.

**Comment by andersjohansson** [comment]
First, cool that you are using it!

The problem seems a little strange, since it's not supposed to try to open any real file, but instead use `orgqda-otag-open` to follow the link (and generate a "collect" buffer).

Are you sure that you have fully loaded orqda? Does it recognize the link type `otag` correctly? If org encounters an unknown link type it seems to suggest "add this as a heading" for me.

Most importantly though: Are you using org version 9 (see variable `org-version`? See `C-h v`+`org-version`). I skipped the compatibility with org version 8 in  8227d4533e717b4c1043ec5c42d8ea0bde674dac (maybe without much information).

(Other custom org link seems to use `::` for splitting, I wonder if that would work. You could try it by changing ":" to "::" in `orgqda-otag-open` and then just manually changing a link to use that format and try to follow it.).

**Comment by andersjohansson** [comment]
I was wrong in my analysis here, and have reworked the syntax now. This should work better on windows. See commit 47cebba
